# Permalinks

# Setup
title: Rosetta open-source
description: Open-source projects by Rosetta
url: http://github.rosettatype.com
baseurl: ""

# About/contact
author:
  name: Rosetta
  url: https://rosettatype.com
  email: info@rosettatype.com

# Build settings
markdown: kramdown

# Articles showed on homepage
articles:
  - title: Eczar
    link: http://github.com/rosettatype/eczar
    description: Latin + Devanagari type family with 5 weights
  - title: Yrsa (ongoing)
    link: http://github.rosettatype.com/yrsa
    description: Latin + Gujarati type family with 5 weights
  - title: repos
    link: http://github.com/rosettatype/repos
    description: Quick and dirty Python script to track multiple Git repositories and easily fetch updates
